version: '3.8'

services:
  pdf2html-api:
    image: ${DOCKER_USERNAME}/pdf2html-api:production
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf2html-production.rule=Host(`api.pdf2html.yourdomain.com`)"
      - "traefik.http.routers.pdf2html-production.tls=true"
      - "traefik.http.services.pdf2html-production.loadbalancer.server.port=8000"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5' 