name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pdf2html-api:latest
          ${{ secrets.DOCKER_USERNAME }}/pdf2html-api:production
          ${{ secrets.DOCKER_USERNAME }}/pdf2html-api:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Hetzner Production
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HETZNER_PRODUCTION_HOST }}
        username: ${{ secrets.HETZNER_USERNAME }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd /opt/pdf2html-api-production
          echo "Pulling latest image..."
          docker-compose pull
          echo "Stopping current containers..."
          docker-compose down
          echo "Starting new containers..."
          docker-compose up -d
          echo "Cleaning up old images..."
          docker image prune -f
          echo "Deployment completed!"
          
    - name: Health check production
      run: |
        sleep 30
        curl -f http://${{ secrets.HETZNER_PRODUCTION_HOST }}:8002/health || exit 1
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "Production deployment completed successfully!"
        # Add notification logic here (Slack, Discord, etc.) 